#!/usr/bin/env bash
##gives information about the file school these kids are bad
if [ -e "school" ]; then
    echo "school file exists"
    if [ -s "school" ]; then
        echo "school file is not empty"
        if [ -f "school" ]; then
            echo "school is a regular file"
	fi
    else
    	echo "school file is empty"
	echo "school is a regular file"
    fi
else
    echo "school file does not exist"
fi
